version: 2.1

jobs:
  build:
    docker:
      - image: docker:19.03.12
    working_directory: /app

    steps:
      - checkout

      - run:
          name: Setup Docker Compose
          command: |
            sudo apt-get update
            sudo apt-get -y install python3-pip
            pip3 install docker-compose

      - run:
          name: Build and Run Docker Compose
          command: |
            docker-compose -f docker-compose.yml up -d

      - run:
          name: Stop Docker Compose
          command: |
            docker-compose -f docker-compose.yml down

      - persist_to_workspace:
          root: ../
          paths:
            - ../binance_bot  # adjust the path based on your project structure

workflows:
  version: 2
  build:
    jobs:
      - build
